### ISSUE TITLE
Rename repo to devices-exporter

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/resource-exporter#2]
Prefer to rename this repo to `devices-exporter`, and add a directory/package for CPU.

**Comment by william-wang** [comment]
We already have a "Devices" repo for GPU device plugin. I am not sure whether it is a bit confusing to use "device-exporter".  
How about "resource-exportor". It is a general name. We can export more kinds of resource in the future.

**Comment by k82cn** [comment]
`resource-exportor` is ok to me :) just make sure we do not bind a repo to specific resources.

**Comment by william-wang** [comment]
Thanks for the suggestion. I changed name to "resource-exportor".
