### ISSUE TITLE
resource-exporter wont trigger update numatopo event at special recover condition

### ISSUE THREAD

**Issue by waiterQ** [volcano-sh/resource-exporter#7]
I met some problems when my resource-exporter recover from stat D, the process goes like this, my resource-exporter got in stat D with sth, and volcano scheduler still work with plugin numa-aware, resource-exporter is in stat D so that k8s start a new resource-exporter, but it is not send a event when found the content is same with before stat D, so scheduler stuck because it is not watch a event from the new resource-exporter.

I think it should force trigger a list-watch event when a new resource-exporter start even though it found content is same
[pr8](https://github.com/volcano-sh/resource-exporter/pull/8) is to fix it

**Comment by william-wang** [comment]
@waiterQ Would you add the reproduce step and the impact?

**Comment by waiterQ** [comment]
**What happened**:
when use volcano scheduler with numa-aware plugin and resource-exporter, suddenly, scheduler is not work, pod is pending but still have resources. 
so, i locate the problem found resource-exporter in stat D and give my reproduce steps, here is my example task:
`apiVersion: apps/v1`
`kind: Deployment`
`metadata:`
`  name: vj-test`
`  labels:`
`    app: nginx`
`spec:`
`  replicas: 1`
`  selector:`
`    matchLabels:`
`      app: nginx`
`  template:`
`    metadata:`
`      labels:`
`        app: nginx`
`      annotations:`
`        volcano.sh/numa-topology-policy: "single-numa-node"`
`    spec:`
`      schedulerName: volcano`
`      containers:`
`        - image: nginx`
`          command: ["/bin/sh", "-c", "sleep 10000"]`
`          imagePullPolicy: IfNotPresent`
`          name: nginx`
`          resources:`
`            requests:`
`              cpu: 1`
`              memory: "100Mi"`
`            limits:`
`              cpu: 1`
`              memory: "100Mi"`

**What you expected to happen**:
scheduler should not stuck after resource-exporter restart.

**How to reproduce it (as minimally and precisely as possible)**:
1. add numa-aware at volcano-scheduler-configmap, start a resource-exporter
2. start a example deployment
3. register stat D to resource-exporter process
`  mkdir -p /sys/fs/cgroup/freezer/test`
`  get pid at host with: ps aux | grep numatopo`
`  echo $pid > /sys/fs/cgroup/freezer/test/tasks`
`  echo "FROZEN" > /sys/fs/cgroup/freezer/test/freezer.state`
`  sleep 1`
`  kill -15 $pid`
4. found resource-exporter in stat D, add example replicas to 3, then reduce replicas to 1, then add replicas to 3
5. now can see 2 pods is pending, but resources is enough. wait a while, a new resource-exporter process start by k8s, but scheduler still stuck.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: branch release-1.7, resource-exporter is master
- Kubernetes version (use `kubectl version`): v1.19, cluster have 1node(4 cpu)
